#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from pathlib import Path

# try to find the timezone except to UTC
symlink_path = "/etc/localtime"
resolved_path = Path(symlink_path).resolve()
timezone = str(resolved_path.relative_to(Path("/usr/share/zoneinfo")))
if not timezone:
    timezone = "UTC"

# Create default vars
agent.set_env("MATOMO_DATABASE_ADAPTER", "mysql")
agent.set_env("MATOMO_DATABASE_TABLES_PREFIX", "matomo")
agent.set_env("MARIADB_DISABLE_UPGRADE_BACKUP", 1)
agent.set_env("MARIADB_AUTO_UPGRADE", 1)
agent.set_env("PHP_MEMORY_LIMIT", 2048)
agent.set_env("MARIADB_INITDB_SKIP_TZINFO", "1")

# agent.set_env("MATOMO_DATABASE_HOST", "localhost")
# agent.set_env("MATOMO_DATABASE_USERNAME", "matomo")
# agent.set_env("MATOMO_DATABASE_PASSWORD", "Nethesis,1234")
# agent.set_env("MATOMO_DATABASE_DBNAME", "matomo")

# Try to parse the stdin as JSON.


